unique_ids:
  forms:
    FormHome: KE5QAZFBYYCGUMDRMYGJUVNAZ56GTWRG
    PageGamesList: '1700682612879239592200737.65143'
    PagePotionsGame: '1700684234290417693397191.6701'
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: FY5QBEP4A7W7YWGZMKRXBGMUMOHFKHQX
    theme.css: KG37TU57KEBCTRFHUZ6PHI2FYQXFJ7Z3
